name: psichic
channels:
  - pytorch  # Highest priority for pytorch and related packages
  - nvidia
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyg::pyg
  - pip
  - pip:
    - rdkit
    - scipy
    - biopython
    - pandas
    - biopandas
    - timeout_decorator
    - py3Dmol
    - umap-learn
    - plotly
    - mplcursors
    - lifelines
    - reprint
    - fair-esm
