name: psichic
channels:
  - pytorch          # Highest priority for pytorch and related packages
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pyg::pyg
  - rdkit             # from conda-forge, not pip
  - pip
  - pip:
      - scipy
      - biopython
      - pandas
      - biopandas
      - timeout_decorator
      - py3Dmol
      - umap-learn
      - plotly
      - mplcursors
      - lifelines
      - reprint
      - fair-esm
